apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cos-fleetshard-connectors-debezium
  labels:
    app: rhoc
spec:
  selector:
    matchLabels:
      cos.bf2.org/operator.type: "debezium-connector-operator"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /metrics
      port: tcp-prometheus
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_cos_bf2_org_connector_id]
          separator: ;
          regex: (.*)
          replacement: $1
          action: replace
          targetLabel: connector_id
        - sourceLabels: [__meta_kubernetes_pod_label_cos_bf2_org_connector_type_id]
          separator: ;
          regex: (.*)
          replacement: $1
          action: replace
          targetLabel: connector_type
        - sourceLabels: [__meta_kubernetes_pod_label_cos_bf2_org_deployment_id]
          separator: ;
          regex: (.*)
          replacement: $1
          action: replace
          targetLabel: deployment_id
