apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-operator-metrics
  labels:
    app: rhoc
spec:
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - path: /metrics
      port: http