project_name: rhoc

builds:
  - id: rhoc
    dir: rhoc
    main: ./cmd/rhoc
    binary: bin/rhoc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

release:
  prerelease: auto
  draft: false
  name_template: "{{.Version}}"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-snapshot"

changelog:
  skip: true
