apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: rhoc
  name: cos-fleetshard-operator-debezium-rules
spec:
  groups:
    - name: cos-fleetshard-operator-debezium
      rules:
        - alert: CosFleetShardOperatorDebeziumTargetDown
          expr: up{container="cos-fleetshard-operator-debezium"} !=1 or absent(up{container="cos-fleetshard-operator-debezium"})
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: 'the cos-fleetshard-operator-debezium target is down'
            description: 'the cos-fleetshard-operator-debezium target has been unable to scrape the {{ $labels.container }} container in the {{ $labels.namespace }} namespace for longer than 10 minutes'
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-tools/blob/main/observability/sops/alerts/cos_fleet_shard_operator_debezium_target_down.adoc'
        - alert: CosFleetShardOperatorDebeziumContainerFrequentlyRestarting
          expr: increase(kube_pod_container_status_restarts_total{container="cos-fleetshard-operator-debezium"}[60m]) > 3
          labels:
            severity: critical
          annotations:
            summary: 'the cos-fleetshard-operator-debezium operator is restarting frequently'
            description: 'the cos-fleetshard-operator-debezium operator container restarted frequently in the last 60 minutes'
            sop_url: 'https://github.com/bf2fc6cc711aee1a0c2a/cos-tools/blob/main/observability/sops/alerts/cos_fleet_shard_operator_debezium_container_frequently_restarting.adoc'
