apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: rhoc
  name: cos-fleetshard-sync-rules
spec:
  groups:
    - name: cos-fleetshard-sync
      rules:
        - alert: CosFleetShardSyncTargetDown
          expr: up{container="cos-fleetshard-sync"} !=1 or absent(up{container="cos-fleetshard-sync"})
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: 'The cos-fleetshard-sync target is down'
            description: 'The cos-fleetshard-sync target has been unable to sync the {{ $labels.container }} container in the {{ $labels.namespace }} namespace for longer than 10 minutes'
            sop_url: 'https://TODO'
        - alert: CosFleetShardSyncContainerFrequentlyRestarting
          expr: increase(kube_pod_container_status_restarts_total{container="cos-fleetshard-sync"}[60m]) > 3
          labels:
            severity: critical
          annotations:
            summary: 'cos-fleetshard-sync is restarting frequently'
            description: 'cos-fleetshard-sync container restarted frequently in the last 60 minutes'
            sop_url: 'https://TODO'
