/*
Connector Management API

Connector Management API is a REST API to manage connectors.

API version: 0.1.0
Contact: rhosak-support@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ConnectorNamespaceMetaAllOf struct for ConnectorNamespaceMetaAllOf
type ConnectorNamespaceMetaAllOf struct {
	ResourceVersion int64                   `json:"resource_version,omitempty"`
	Quota           ConnectorNamespaceQuota `json:"quota,omitempty"`
}
