/*
 * Connector Service Fleet Manager
 *
 * Connector Service Fleet Manager is a Rest API to manage connectors.
 *
 * API version: 0.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public
// ServiceAccount struct for ServiceAccount
type ServiceAccount struct {
	ClientId string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
}
