/*
Connector Service Fleet Manager

Connector Service Fleet Manager is a Rest API to manage connectors.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ConnectorNamespaceTenantKind the model 'ConnectorNamespaceTenantKind'
type ConnectorNamespaceTenantKind string

// List of ConnectorNamespaceTenantKind
const (
	CONNECTORNAMESPACETENANTKIND_USER         ConnectorNamespaceTenantKind = "user"
	CONNECTORNAMESPACETENANTKIND_ORGANISATION ConnectorNamespaceTenantKind = "organisation"
)
