/*
Connector Management API

Connector Management API is a REST API to manage connectors.

API version: 0.1.0
Contact: rhosak-support@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ConnectorNamespaceTenantKind the model 'ConnectorNamespaceTenantKind'
type ConnectorNamespaceTenantKind string

// List of ConnectorNamespaceTenantKind
const (
	CONNECTORNAMESPACETENANTKIND_USER         ConnectorNamespaceTenantKind = "user"
	CONNECTORNAMESPACETENANTKIND_ORGANISATION ConnectorNamespaceTenantKind = "organisation"
)
