/*
Connector Management API

Connector Management API is a REST API to manage connectors.

API version: 0.1.0
Contact: rhosak-support@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package public

// ServiceAccount struct for ServiceAccount
type ServiceAccount struct {
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
}
