// begin header
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:numbered:
:toc: macro
:toc-title: pass:[<b>Table of Contents</b>]
// end header
= Some SOP/Alert Name

toc::[]

== Description

// Delete this comment and all subsequent comments as you fill in the template. This ensures that numbered lists are not reset back to 1.
// Include the following step in every alert SOP, changing required parts
The purpose of this SOP is to describe the process of resolving the alert `someAlertName`.

// Include the following step in every alert SOP, changing required parts
The source of the alert is the `someAlertMetric` metric. It fires when the condition foo is true.

Add other helpful information about the alert here if necessary. However, avoid a wall of text. This section should be short and include only information critical to resolving the alert. If you want to include extra information that can provide context for the alert use the link:#_further_reading[Further Reading] section below and a note here that more information is available.

== Prerequisites

// Include the following steps in every alert SOP
* Access to the OSD cluster via either Kafka_SRE IDP or Backplane.
* Permission to run managed scripts on the cluster.
* The ID of the affected Kafka(s). This is provided by the alert via a label. It should look something like this: `c5ff3f4ctr234ihcgr8g`.
// Include any extra steps
* Add any other information that is needed or access to any system that is needed.

== Execute/Resolution

// Include this as the first step in every alert SOP
. Run the get-kafka-instance-state managed script.
+
[source,sh]
----
ocm backplane managedjob create CEE/get-kafka-instance-state -p resource_namespace=<KAFKA_CLUSTER_NAMESPACE>
# Take note of the ID of the created job

oc logs $JOB_ID -n openshift-backplane-managed-scripts | tar xzf -
# The content will appear in a directory called `inspect.<KAFKA_CLUSTER_NAMESPACE>.<EPOCH_TIMESTAMP>` in the working directory.
----

// Include the following step if applicable, changing necessary information
. Is there a Grafana dashboard that can be opened to keep an eye on the state of things while attempting to resolve?

. Define step-by-step how to resolve the alert. Each step should be clear and concise and accompanied by an example command that can be copied, where applicable. E.g

.. Delete this pod
+
`command blah blah`
.. Apply this yaml file `blah.yml`

// Include the following as the last step in every alert SOP
. If the alert is not resolved move to the Troubleshooting section below.

== Validate

What steps are required to verify that the procedure has been followed correctly and the required changes have been implemented correctly, with the desired outcome.

//Include the following steps in every alert SOP
. Check the alert is no longer firing.
. Check the dashboard are shows x,y,z.
// Add any extra steps
. Add more as necessary

== Troubleshooting

Include other steps here that can help track down the issue but are of an investigative nature and do not have a clear action. For example:

* Check the logs of component foo and follow up on any errors you notice.
* Check if component foo is running and follow up with SRE-P if necessary.
* Check if MAS-SSO is functioning and communication is possible. https://grafana.app-sre.devshift.net/d/_LLa8q_Gk/mas-sso-monitoring?orgId=1[MAS-SSO Dashboard]

// Include the following step in every alert SOP
* If the above hasn't worked contact engineering:
** Use the Kafka Service Impacting Gchat channel during business hours.
** Use the https://docs.google.com/document/d/1Uc2Rq-o0UWi7ryoG-OA7CT5DDOtZFHbOf_neFTni5yM/edit#heading=h.o77j1tlspb6[Engaging Engineering document] to escalate if out of hours and/or no response on gchat.

== Further Reading

Put any extra information about the alert here. I.e. Information that isn't critical to resolving to alert but might help SRE who's not familiar with the alert understand it and it's implications if they want to.
