/*
Connector Service Fleet Manager Admin APIs

Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

import (
	"time"
)

// ConnectorDeploymentAdminViewAllOfMetadata struct for ConnectorDeploymentAdminViewAllOfMetadata
type ConnectorDeploymentAdminViewAllOfMetadata struct {
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ResourceVersion int64     `json:"resource_version"`
	ResolvedSecrets bool      `json:"resolved_secrets"`
	// Name-value string annotations for resource
	Annotations map[string]string `json:"annotations,omitempty"`
}
