/*
 * Connector Service Fleet Manager Admin APIs
 *
 * Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.
 *
 * API version: 0.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

// ConnectorAvailableOperatorUpgradeOperator struct for ConnectorAvailableOperatorUpgradeOperator
type ConnectorAvailableOperatorUpgradeOperator struct {
	AssignedId  string `json:"assigned_id,omitempty"`
	AvailableId string `json:"available_id,omitempty"`
}
