/*
Connector Service Fleet Manager Admin APIs

Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

// ConnectorStatusStatus struct for ConnectorStatusStatus
type ConnectorStatusStatus struct {
	State ConnectorState `json:"state,omitempty"`
	Error string         `json:"error,omitempty"`
}
