/*
 * Connector Service Fleet Manager Admin APIs
 *
 * Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.
 *
 * API version: 0.0.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

// ConnectorClusterState the model 'ConnectorClusterState'
type ConnectorClusterState string

// List of ConnectorClusterState
const (
	CONNECTORCLUSTERSTATE_DISCONNECTED ConnectorClusterState = "disconnected"
	CONNECTORCLUSTERSTATE_READY        ConnectorClusterState = "ready"
	CONNECTORCLUSTERSTATE_DELETING     ConnectorClusterState = "deleting"
)
