/*
Connector Service Fleet Manager Admin APIs

Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

// ConnectorAdminViewList struct for ConnectorAdminViewList
type ConnectorAdminViewList struct {
	Kind  string               `json:"kind"`
	Page  int32                `json:"page"`
	Size  int32                `json:"size"`
	Total int32                `json:"total"`
	Items []ConnectorAdminView `json:"items"`
}
