/*
Connector Service Fleet Manager Admin APIs

Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

// ConnectorNamespaceWithTenantRequestAllOf struct for ConnectorNamespaceWithTenantRequestAllOf
type ConnectorNamespaceWithTenantRequestAllOf struct {
	ClusterId string                   `json:"cluster_id,omitempty"`
	Tenant    ConnectorNamespaceTenant `json:"tenant,omitempty"`
	// Namespace expiration timestamp in RFC 3339 format
	Expiration string `json:"expiration,omitempty"`
}
