/*
Connector Service Fleet Manager Admin APIs

Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

// ConnectorAvailableTypeUpgrade An available type upgrade for a connector
type ConnectorAvailableTypeUpgrade struct {
	ConnectorId     string                                     `json:"connector_id,omitempty"`
	NamespaceId     string                                     `json:"namespace_id,omitempty"`
	ConnectorTypeId string                                     `json:"connector_type_id,omitempty"`
	Channel         string                                     `json:"channel,omitempty"`
	ShardMetadata   ConnectorAvailableTypeUpgradeShardMetadata `json:"shard_metadata,omitempty"`
}
