/*
Connector Service Fleet Manager Admin APIs

Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.

API version: 0.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package admin

// ConnectorNamespaceStatus struct for ConnectorNamespaceStatus
type ConnectorNamespaceStatus struct {
	State              ConnectorNamespaceState `json:"state"`
	Version            string                  `json:"version,omitempty"`
	ConnectorsDeployed int32                   `json:"connectors_deployed"`
	Error              string                  `json:"error,omitempty"`
}
