{
 "title": "CamelK Operator",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang",
  "camel",
  "operator"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Camel K Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconciliation Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(camel_k_reconciliation_duration_seconds_count[5m])",
     "legendFormat": "{{kind}}-{{result}}"
    }
   ]
  },
  {
   "title": "Integration time to readiness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(camel_k_integration_first_readiness_seconds_bucket{le=\"60\"}[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Golang Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "mspan_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "mspan_sys_bytes"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "mcache_inuse_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "hash_sys_bytes"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "gc_sys_bytes"
    },
    {
     "expr": "go_memstats_other_sys_bytes{container=\"camel-k-operator\"} - go_memstats_other_sys_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "sys_bytes"
    },
    {
     "expr": "go_memstats_next_gc_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "gc_bytes"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "heap_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_released_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "heap_released_bytes"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "stack_inuse"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "stack_sys"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{container=\"camel-k-operator\"}",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{container=\"camel-k-operator\"} - go_memstats_frees_total{container=\"camel-k-operator\"}",
     "legendFormat": "mallocs_total"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{container=\"camel-k-operator\"}[1m])",
     "legendFormat": "mallocs_total"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "graph",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{container=\"camel-k-operator\"}[1m])",
     "legendFormat": "lookups"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{container=\"camel-k-operator\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{container=\"camel-k-operator\"}[1m])",
     "legendFormat": "alloc_bytes_total"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{container=\"camel-k-operator\"}",
     "legendFormat": "duration-{{quantile}}"
    }
   ]
  }
 ]
}