{
 "title": "CamelK Connectors",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(application_camel_route_count{},namespace)"
   },
   {
    "name": "pod",
    "label": "Connector",
    "query": "label_values(application_camel_route_count{namespace=\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_camel_context_uptime_seconds{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(vendor_memoryPool_usage_bytes{namespace=\"$namespace\", pod=\"$pod\"})*100/sum(vendor_memoryPool_usage_max_bytes{namespace=\"$namespace\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_context_exchanges_total{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Exchanges Total"
    },
    {
     "expr": "application_camel_context_exchanges_completed_total{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Exchanges Completed"
    },
    {
     "expr": "application_camel_context_exchanges_failed_total{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Exchanges Failed"
    },
    {
     "expr": "application_camel_context_exchanges_inflight_count{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Exchanges Inflight"
    }
   ]
  },
  {
   "title": "Total Routes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "application_camel_route_count{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  { "title": "Camel Specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Exchange Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(application_camel_exchange_processing_seconds_count{namespace=\"$namespace\", pod=\"$pod\"}[60m])",
     "legendFormat": "Rate of increase in Exchange Processing Time"
    }
   ]
  },
  {
   "title": "Exchanges Completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(application_camel_context_exchanges_completed_total{namespace=\"$namespace\", pod=\"$pod\"}[60m])",
     "legendFormat": "{{camelContext}}"
    }
   ]
  },
  {
   "title": "Exchange Processing Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_camel_exchange_processing_rate_per_second{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "Exchange processing rate per second"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Vendor CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_cpu_systemCpuLoad_percent{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "System Load Percent"
    }
   ]
  },
  {
   "title": "Base CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Process Load Percent"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "System Load Average"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Vendor Memory NonHeap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_memory_usedNonHeap_bytes{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "vendor_memory_committedNonHeap_bytes{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Vendor Memory Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_memoryPool_usage_bytes{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(vendor_memoryPool_usage_max_bytes{namespace=\"$namespace\", pod=\"$pod\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Base Memory Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "base_memory_committedHeap_bytes{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "base_memory_maxHeap_bytes{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Network I/O Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\", name=~\".*_mctr-.*\"}[10m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=\"$pod\", name=~\".*_mctr-.*\"}[10m]))",
     "legendFormat": "Sent"
    }
   ]
  }
 ]
}