{
 "title": "Connectors",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connectors Count (selected time)",
   "type": "stat",
   "description": "Total Connectors, CamelK Connectors vs Debezium Connectors running in the selected time range.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(up{container=\"integration\"}[$__range]))",
     "legendFormat": "Total Connectors"
    },
    {
     "expr": "count(max_over_time(application_camel_context_status{camelContext=\"camel-1\"}[$__range]))",
     "legendFormat": "CamelK Connectors"
    },
    {
     "expr": "sum(max_over_time(up{container=\"integration\"}[$__range])) - count(max_over_time(application_camel_context_status{camelContext=\"camel-1\"}[$__range]))",
     "legendFormat": "Debezium connectors"
    }
   ]
  },
  {
   "title": "Availability (selected time)",
   "type": "gauge",
   "description": "The percentage of time that the Connectors are available in the selected time range.",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(up{container=\"integration\"}[$__range])) / sum(max_over_time(up{container=\"integration\"}[$__range])) * 100"
    }
   ]
  },
  {
   "title": "Connectors Running / Crashing",
   "type": "graph",
   "description": "CamelK Connectors, Debezium Connectors, and crashing Connectors over time. Crashing connectors are only shown when they are crashing(connectors that successfully got created previously and now crashing). ",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total{container=\"integration\"}[10m]) >3)",
     "legendFormat": "Connectors Failing"
    },
    {
     "expr": "count(application_camel_context_status{camelContext=\"camel-1\"})",
     "legendFormat": "CamelK Connectors"
    },
    {
     "expr": "sum(up{container=\"integration\"}) - count(application_camel_context_status{camelContext=\"camel-1\"})",
     "legendFormat": "Debezium Connectors"
    }
   ]
  },
  { "title": "CamelK Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Exchanges Count (selected time)",
   "type": "stat",
   "description": "Total, Completed, Failed, and Currently Inflight Exchanges for all the CamelK Connectors.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_total[$__range]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_completed_total[$__range]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_failed_total[$__range]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(application_camel_context_exchanges_inflight_count)",
     "legendFormat": "Inflight Currently"
    }
   ]
  },
  {
   "title": "Exchanges Processed (selected time)",
   "type": "gauge",
   "description": "Percentage of exchanges completed in the selected time range.",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(application_camel_context_exchanges_completed_total[$__range])) / sum(max_over_time(application_camel_context_exchanges_total[$__range])) * 100"
    }
   ]
  },
  {
   "title": "No. of Exchanges",
   "type": "graph",
   "description": "Exchanges Quantitative Information over time",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(application_camel_context_exchanges_total)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(application_camel_context_exchanges_completed_total)",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": " Camel Connectors / Reconciliation Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(camel_k_reconciliation_duration_seconds_count[5m])",
     "legendFormat": "{{kind}}-{{result}}"
    }
   ]
  },
  {
   "title": "CamelK Connectors ",
   "type": "table",
   "description": "CamelK Connectors, their respective Namespace, and their time since creation. Click on the connector to see that connector's detailed dashboard. Filter column using the Filter option next to the column header.",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "application_camel_context_status{camelContext=\"camel-1\"}"
    },
    {
     "expr": "application_camel_context_uptime_seconds"
    }
   ]
  },
  { "title": "Debezium Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Debezium / Failed Reconciliation per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(strimzi_reconciliations_failed_total[1h])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  }
 ]
}