{
 "title": "Debezium Connectors",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(debezium_metrics_Connected{},namespace)"
   },
   {
    "name": "connector_id",
    "label": "Connector ID",
    "query": "label_values(debezium_metrics_Connected{namespace=\"$namespace\"}, connector_id)"
   },
   {
    "name": "pod",
    "label": "Connector",
    "query": "label_values(debezium_metrics_Connected{namespace=\"$namespace\", connector_id=\"$connector_id\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connector Type",
   "type": "stat",
   "description": "Type of the Debezium Connector",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Connector ID",
   "type": "stat",
   "description": "Connector ID of the Debezium Connector",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "description": "Namespace of the Debezium Connector",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Deployment ID",
   "type": "stat",
   "description": "Deployment ID of the Debezium Connector",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_Connected{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  { "title": "Debezium Specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Milliseconds Behind Source",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsBehindSource{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "Milliseconds Behind Source"
    }
   ]
  },
  {
   "title": "Milliseconds Since Last Event",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{pod=\"$pod\", namespace=\"$namespace\", context=\"streaming\"}",
     "legendFormat": "Streaming"
    },
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{pod=\"$pod\", namespace=\"$namespace\", context=\"snapshot\"}",
     "legendFormat": "Snapshot"
    }
   ]
  },
  {
   "title": "Total Number of Events Seen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{pod=\"$pod\", namespace=\"$namespace\", context=\"streaming\"}",
     "legendFormat": "Streaming"
    },
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{pod=\"$pod\", namespace=\"$namespace\", context=\"snapshot\"}",
     "legendFormat": "Snapshot"
    }
   ]
  },
  {
   "title": "Queue Remaining Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{pod=\"$pod\", namespace=\"$namespace\", context=\"streaming\"}",
     "legendFormat": "Streaming"
    },
    {
     "expr": "debezium_metrics_QueueRemainingCapacity{pod=\"$pod\", namespace=\"$namespace\", context=\"snapshot\"}",
     "legendFormat": "Snapshot"
    }
   ]
  },
  { "title": "CPU ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Total CPU Usage",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  { "title": "JVM Specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Maximum JVM Memory Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{pod=\"$pod\", namespace=\"$namespace\", area=\"heap\"}",
     "legendFormat": "Heap "
    },
    {
     "expr": "jvm_memory_bytes_max{pod=\"$pod\", namespace=\"$namespace\", area=\"nonheap\"}",
     "legendFormat": "Nonheap"
    }
   ]
  },
  {
   "title": "Total JVM Bytes Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{pod=\"$pod\", namespace=\"$namespace\", area=\"heap\"}",
     "legendFormat": "Heap"
    },
    {
     "expr": "jvm_memory_bytes_used{pod=\"$pod\", namespace=\"$namespace\", area=\"nonheap\"}",
     "legendFormat": "Nonheap"
    }
   ]
  },
  { "title": "Kafka Specific", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Connector Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connector_status{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Connector Task Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_status{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Total Requests in Flight",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_producer_requests_in_flight{pod=\"$pod\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Outgoing Bytes Total",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_outgoing_byte_total{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Outgoing Bytes Total"
    }
   ]
  }
 ]
}