{
 "title": "Managed Connector Service",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{}, namespace)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\",area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\", service=\"$service\"}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\", service=\"$service\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$namespace\", service=\"$service\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Managed Connector Lifecycle Phases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Reconcile Monitor Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cos_fleetshard_controller_connectors_reconcile_monitor_time_seconds_max{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "cos_fleetshard_controller_connectors_reconcile_monitor_time_seconds{service=\"$service\", namespace=\"$namespace\", quantile=\"0.95\"}",
     "legendFormat": "Q95"
    }
   ]
  },
  {
   "title": "KameletBinding Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "camel_apache_org_v1alpha1_KameletBinding_time_seconds_max{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "camel_apache_org_v1alpha1_KameletBinding_time_seconds{service=\"$service\", namespace=\"$namespace\", quantile=\"0.95\"}",
     "legendFormat": "Q95"
    }
   ]
  },
  {
   "title": "Event Operators Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cos_fleetshard_controller_event_operators_time_seconds_max{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "cos_fleetshard_controller_event_operators_time_seconds{service=\"$service\", namespace=\"$namespace\", quantile=\"0.95\"}",
     "legendFormat": "Q95"
    }
   ]
  },
  {
   "title": "Connectors Reconcile Augmentation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cos_fleetshard_controller_connectors_reconcile_augmentation_time_seconds_max{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "cos_fleetshard_controller_connectors_reconcile_augmentation_time_seconds{service=\"$service\", namespace=\"$namespace\", quantile=\"0.95\"}",
     "legendFormat": "Q95"
    }
   ]
  },
  {
   "title": "Event Secrets Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cos_fleetshard_controller_event_secrets_time_seconds_max{service=\"$service\", namespace=\"$namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "cos_fleetshard_controller_event_secrets_time_seconds{service=\"$service\", namespace=\"$namespace\", quantile=\"0.95\"}",
     "legendFormat": "Q95"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"$service\", namespace=\"$namespace\"}[2m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{status!~\"5..\", namespace=\"$namespace\",service=\"$service\"}[2m]))/sum(rate(http_server_requests_seconds_count{status!~\"5..\",namespace=\"$namespace\",service=\"$service\"}[2m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{status!~\"5..\",namespace=\"$namespace\",service=\"$service\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"$namespace\",service=\"$service\",status=~\"5..\"}[5m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\",service=\"$service\",area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$namespace\",service=\"$service\",})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{namespace=\"$namespace\",service=\"$service\",})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$namespace\",service=\"$service\",})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_rss_bytes{namespace=\"$namespace\",service=\"$service\",}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_swap_bytes{namespace=\"$namespace\",service=\"$service\",}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_rss_bytes{namespace=\"$namespace\",service=\"$service\",} + process_memory_swap_bytes{namespace=\"$namespace\",service=\"$service\",}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{namespace=\"$namespace\",service=\"$service\",}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{namespace=\"$namespace\",service=\"$service\",}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{namespace=\"$namespace\",service=\"$service\",}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{namespace=\"$namespace\",service=\"$service\",}",
     "legendFormat": "system-1m"
    },
    {
     "expr": "system_cpu_count{namespace=\"$namespace\",service=\"$service\",}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{namespace=\"$namespace\",service=\"$service\",}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=\"$namespace\",service=\"$service\",}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{namespace=\"$namespace\",service=\"$service\",}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max_files{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }, "repeat": "persistence_counts" },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\", service=\"$service\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Memory Pools (Non-Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\", service=\"$service\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{namespace=\"$namespace\", service=\"$service\"}[2m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{namespace=\"$namespace\", service=\"$service\"}[1m])/rate(jvm_gc_pause_seconds_count{namespace=\"$namespace\", service=\"$service\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{namespace=\"$namespace\", service=\"$service\"}[2m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{namespace=\"$namespace\", service=\"$service\"}[2m])",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$service\"}[2m])",
     "legendFormat": "delta-1m"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", id=\"direct\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{namespace=\"$namespace\", service=\"$service\", id=\"direct\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{namespace=\"$namespace\", service=\"$service\", id=\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", id=\"mapped\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{namespace=\"$namespace\", service=\"$service\", id=\"mapped\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{namespace=\"$namespace\", service=\"$service\", id=\"mapped\"}",
     "legendFormat": "count"
    }
   ]
  },
  { "title": "HTTP Edpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Total number of requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\"}[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Average inbound request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"$service\"}[4m]) / rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\"}[4m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Maximum inbound request duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Sum of the duration of every request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{namespace=\"$namespace\", service=\"$service\"}[2m])",
     "legendFormat": "{{method}} - {{uri}} - {{status}}"
    }
   ]
  }
 ]
}