= rhoc-cli

== Installing the RHOC CLI

You can install `rhoc` on Linux, macOS, or Windows by downloading the related binary from the `rhoc` https://github.com/bf2fc6cc711aee1a0c2a/cos-tools/releasess[Releases page]

== Logging in to RHOC

After `rhoc` is installed, you can log in to access your application services.

.Prerequisites

* You must have an account to access Red Hat OpenShift Application Services.
* You've installed the `rhoc` CLI.

.Procedure

. In a terminal, log in to `rhoc`.
+
[source,shell]
----
$ rhoc login
----
+
You are redirected to your web browser at https://sso.redhat.com[^].

. Enter your credentials to log in to your Red Hat account.
+
Welcome pages in the browser notify you that you've been logged in to `rhoc` successfully.
In your terminal, the `rhoc login` command indicates that you're logged in.


=== Poiting to different environment

It is possible to login to a different environment by setting the related flags. 

[source,shell]
----
$ rhoc login --mas-auth-url=$RHOC_MAS_AUTH_URL --auth-url=$RHOC_AUTH_URL --api-gateway=$RHOC_API_GATEWAY
----


== Logging out of RHOC

You can log out from the `rhoc` CLI by using the `rhoc logout` command.

.Procedure

[source,shell]
-----
$ rhoc logout
-----

